// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/repo/[id]" | "/repo/[id]/config" | "/settings" | "/task/[id]"
type AppRouteHandlerRoutes = "/api/auth/github/callback" | "/api/auth/github/start" | "/api/auth/logout" | "/api/auth/session" | "/api/github/installations" | "/api/github/installations/[installationId]/repositories" | "/api/github/webhooks" | "/api/health" | "/api/meta/bootstrap" | "/api/repos" | "/api/repos/[repoId]" | "/api/repos/[repoId]/config" | "/api/repos/[repoId]/files" | "/api/repos/[repoId]/tasks" | "/api/repos/import" | "/api/tasks/[taskId]" | "/api/tasks/[taskId]/preview" | "/api/tasks/[taskId]/progress"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/github/callback": {}
  "/api/auth/github/start": {}
  "/api/auth/logout": {}
  "/api/auth/session": {}
  "/api/github/installations": {}
  "/api/github/installations/[installationId]/repositories": { "installationId": string; }
  "/api/github/webhooks": {}
  "/api/health": {}
  "/api/meta/bootstrap": {}
  "/api/repos": {}
  "/api/repos/[repoId]": { "repoId": string; }
  "/api/repos/[repoId]/config": { "repoId": string; }
  "/api/repos/[repoId]/files": { "repoId": string; }
  "/api/repos/[repoId]/tasks": { "repoId": string; }
  "/api/repos/import": {}
  "/api/tasks/[taskId]": { "taskId": string; }
  "/api/tasks/[taskId]/preview": { "taskId": string; }
  "/api/tasks/[taskId]/progress": { "taskId": string; }
  "/dashboard": {}
  "/repo/[id]": { "id": string; }
  "/repo/[id]/config": { "id": string; }
  "/settings": {}
  "/task/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
