// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/repo/[id]/config/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/repo/[id]/config">> = Specific
  const handler = {} as typeof import("../../src/app/repo/[id]/config/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/repo/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/repo/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/repo/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/task/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/task/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/task/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/github/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/github/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/github/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/github/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/github/start">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/github/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/github/installations/[installationId]/repositories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/installations/[installationId]/repositories">> = Specific
  const handler = {} as typeof import("../../src/app/api/github/installations/[installationId]/repositories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/github/installations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/installations">> = Specific
  const handler = {} as typeof import("../../src/app/api/github/installations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/github/webhooks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/webhooks">> = Specific
  const handler = {} as typeof import("../../src/app/api/github/webhooks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/meta/bootstrap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta/bootstrap">> = Specific
  const handler = {} as typeof import("../../src/app/api/meta/bootstrap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/repos/[repoId]/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/repos/[repoId]/config">> = Specific
  const handler = {} as typeof import("../../src/app/api/repos/[repoId]/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/repos/[repoId]/files/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/repos/[repoId]/files">> = Specific
  const handler = {} as typeof import("../../src/app/api/repos/[repoId]/files/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/repos/[repoId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/repos/[repoId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/repos/[repoId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/repos/[repoId]/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/repos/[repoId]/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/api/repos/[repoId]/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/repos/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/repos/import">> = Specific
  const handler = {} as typeof import("../../src/app/api/repos/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/repos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/repos">> = Specific
  const handler = {} as typeof import("../../src/app/api/repos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[taskId]/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[taskId]/preview">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[taskId]/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[taskId]/progress/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[taskId]/progress">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[taskId]/progress/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[taskId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[taskId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[taskId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
